### ISSUE TITLE
Upload app.zip as an artifac

### ISSUE THREAD

**Issue by studiapawelp** [devops-laba-it/image-uploader#1]
```
    - name: Upload app.zip as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-archive
        path: app.zip

```
